name: olive_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  image_picker: ^0.8.5+3
  flutter_svg: ^1.0.0
  lottie: ^1.4.3
  http: ^1.2.1
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.13
  flutter_colorpicker: ^1.0.3
  syncfusion_flutter_charts: ^21.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/animation.json
    - lib/assets/classes/classe1.png
    - lib/assets/classes/classe2.png
    - lib/assets/classes/classe3.png
    - lib/assets/classes/classe4.png
    - lib/assets/classes/classe5.png
    - lib/assets/classes/classe6.png
    - lib/assets/classes/classe7.png
    - lib/assets/classes/classe8.png
  fonts:
    - family: Rawline
      fonts:
        - asset: lib/assets/rawline-400.ttf
        - asset: lib/assets/rawline-400.ttf
          weight: 700
        - asset: lib/assets/rawline-400.ttf
          style: italic

